### PR TITLE
CXP-975: Optimize read operation on ByteArrayInputStream

### PR DESCRIPTION
**Pull request by ramanenka**
Todo:
- [x] add more tests

### CODE REVIEW

**Comment by morozov** [comment]
@ramanenka let's move the merge from upstream to a separate PR, since it's unrelated to the performance improvement. Code-wise looks good so far.

**Comment by morozov** [comment]
> add more tests

Testing-wise it should be enough to cover three scenarios:
1. Reading within the block (`len <= blockLength`).
2. Reading beyond block (`len > blockLength`). The behavior here is the least obvious, so it should be covered first of all.
3. Reading without entering a block (`blockLength = -1`).

**Comment by ramanenka** [comment]
> let's move the merge from upstream to a separate PR

I've created #3

**Comment by ramanenka** [comment]
Also I've submitted the patch upstream: https://github.com/osheroff/mysql-binlog-connector-java/pull/34

**Comment by morozov** [comment]
Looks good! Please rebase.

**Review by morozov — APPROVED** [review]

**Pull request merged**
